### ISSUE TITLE
Template for everything

### ISSUE THREAD

**Issue by DmitryBarskov** [DmitryBarskov/rails-template#14]
I want to see next issues:

- [x] #22
- [x] #25
- [x] #26
- [x] #29
- [x] #27
- [x] #30
- [x] #28
- [x] #31
- [x] #32
- [x] #33
- [x] #24
- [x] #23

Create an issue for each bullet and describe the proposed template

**Comment by KilinMikhail** [comment]
Hello, can you add issues for these templates? I can get somethiing from this list
