### ISSUE TITLE
Template for `slim`

### ISSUE THREAD

**Issue by RasimKhusaenov** [DmitryBarskov/rails-template#19]
## Summary
Add to Gemfile: `gem 'slim'`
It may also ask if we need to use gem for template generators. And add `gem 'slim-rails'`.
Success!

**Comment by DmitryBarskov** [comment]
Personally I don't like slim and prefer ERB.

For the slim I can also suggest installing `slim-lint` and converting existing ERB files to slim using https://github.com/slim-template/html2slim.

What do you think?

**Comment by RasimKhusaenov** [comment]
Ok, but is it about what we like, or should we create templates for everything that might be useful in a project or a larger scenario?

**Comment by RasimKhusaenov** [comment]
I'm not sure it's safe. If the project is large, the converter may not see the details and everything will break, right?

**Comment by DmitryBarskov** [comment]
It is supposed to work unambiguously. So I think no. Maybe we can test it somehow?
