### ISSUE TITLE
Does it mean that in this case DatabaseCleaner is useless? Or we need to add them?

### ISSUE THREAD

**Issue by DenisZackharov** [DmitryBarskov/rails-template#36]
https://github.com/DmitryBarskov/rails-template/blob/c68472bae0840f1fee7f96a1a6c64eaea293aa76/templates/files/spec/rails_helper.rb#L21

**Comment by DenisZackharov** [comment]
@DmitryBarskov

**Comment by DmitryBarskov** [comment]
Hey @DenisZackharov!

Is DatabaseCleaner useless? Not completely. I see it has its use cases for non AR ORMs (see the list here https://github.com/DatabaseCleaner/database_cleaner#list-of-adapters). Besides that with this gem you can customize database cleaning more precisely.

In any other cases there is no need to use this gem.

Thx for the question. Close the issue if I've answered your question.
